export const SET_WORRY_TIMES = 'SET_WORRY_TIMES';
export const APPEND_WORRY_TIME = 'APPEND_WORRY_TIME';
export const REMOVE_WORRY_TIME = 'REMOVE_WORRY_TIME';
export const UPDATE_WORRY_TIME = 'UPDATE_WORRY_TIME';

export const APPEND_WORRY = 'APPEND_WORRY';
export const UPDATE_WORRY = 'UPDATE_WORRY';
export const REMOVE_WORRY = 'REMOVE_WORRY';
